<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="26" passed="11" failed="1" skipped="12">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-20T13:13:50 IST" name="HRMS" finished-at="2023-02-20T13:17:57 IST" duration-ms="247870">
    <groups>
    </groups>
    <test started-at="2023-02-20T13:13:50 IST" name="HRMS automation masters" finished-at="2023-02-20T13:17:57 IST" duration-ms="247870">
      <class name="com.hrms.masters.tests.MastersPersonalTest">
        <test-method signature="LoginTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5]" started-at="2023-02-20T13:17:56 IST" name="LoginTest" finished-at="2023-02-20T13:17:56 IST" duration-ms="3" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.hrms.masters.tests.MastersPersonalTest.LoginTest(MastersPersonalTest.java:10)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method signature="BloodGroupEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5]" started-at="2023-02-20T13:17:56 IST" name="BloodGroupEditTest" finished-at="2023-02-20T13:17:56 IST" depends-on-methods="com.hrms.masters.tests.MastersPersonalTest.LoginTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MastersPersonalTest.BloodGroupEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MastersPersonalTest.BloodGroupEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BloodGroupEditTest -->
        <test-method signature="BloodGroupTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5]" started-at="2023-02-20T13:17:56 IST" name="BloodGroupTest" finished-at="2023-02-20T13:17:56 IST" depends-on-methods="com.hrms.masters.tests.MastersPersonalTest.LoginTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MastersPersonalTest.BloodGroupTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MastersPersonalTest.BloodGroupTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BloodGroupTest -->
        <test-method signature="IdentificationProofEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5]" started-at="2023-02-20T13:17:56 IST" name="IdentificationProofEditTest" finished-at="2023-02-20T13:17:56 IST" depends-on-methods="com.hrms.masters.tests.MastersPersonalTest.LoginTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MastersPersonalTest.IdentificationProofEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MastersPersonalTest.IdentificationProofEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- IdentificationProofEditTest -->
        <test-method signature="IdentificationProofTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5]" started-at="2023-02-20T13:17:56 IST" name="IdentificationProofTest" finished-at="2023-02-20T13:17:56 IST" depends-on-methods="com.hrms.masters.tests.MastersPersonalTest.LoginTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MastersPersonalTest.IdentificationProofTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MastersPersonalTest.IdentificationProofTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- IdentificationProofTest -->
        <test-method signature="LanguageEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5]" started-at="2023-02-20T13:17:56 IST" name="LanguageEditTest" finished-at="2023-02-20T13:17:56 IST" depends-on-methods="com.hrms.masters.tests.MastersPersonalTest.LoginTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MastersPersonalTest.LanguageEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MastersPersonalTest.LanguageEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LanguageEditTest -->
        <test-method signature="LanguageTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5]" started-at="2023-02-20T13:17:56 IST" name="LanguageTest" finished-at="2023-02-20T13:17:56 IST" depends-on-methods="com.hrms.masters.tests.MastersPersonalTest.LoginTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MastersPersonalTest.LanguageTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MastersPersonalTest.LanguageTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LanguageTest -->
        <test-method signature="NationalityEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5]" started-at="2023-02-20T13:17:57 IST" name="NationalityEditTest" finished-at="2023-02-20T13:17:57 IST" depends-on-methods="com.hrms.masters.tests.MastersPersonalTest.LoginTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MastersPersonalTest.NationalityEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MastersPersonalTest.NationalityEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NationalityEditTest -->
        <test-method signature="NationalityTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5]" started-at="2023-02-20T13:17:57 IST" name="NationalityTest" finished-at="2023-02-20T13:17:57 IST" depends-on-methods="com.hrms.masters.tests.MastersPersonalTest.LoginTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MastersPersonalTest.NationalityTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MastersPersonalTest.NationalityTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NationalityTest -->
        <test-method signature="RelationShipTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5]" started-at="2023-02-20T13:17:57 IST" name="RelationShipTest" finished-at="2023-02-20T13:17:57 IST" depends-on-methods="com.hrms.masters.tests.MastersPersonalTest.LoginTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MastersPersonalTest.RelationShipTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MastersPersonalTest.RelationShipTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RelationShipTest -->
        <test-method signature="RelationshipEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5]" started-at="2023-02-20T13:17:57 IST" name="RelationshipEditTest" finished-at="2023-02-20T13:17:57 IST" depends-on-methods="com.hrms.masters.tests.MastersPersonalTest.LoginTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MastersPersonalTest.RelationshipEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MastersPersonalTest.RelationshipEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RelationshipEditTest -->
        <test-method signature="ReligionEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5]" started-at="2023-02-20T13:17:57 IST" name="ReligionEditTest" finished-at="2023-02-20T13:17:57 IST" depends-on-methods="com.hrms.masters.tests.MastersPersonalTest.LoginTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MastersPersonalTest.ReligionEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MastersPersonalTest.ReligionEditTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReligionEditTest -->
        <test-method signature="ReligionTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5]" started-at="2023-02-20T13:17:57 IST" name="ReligionTest" finished-at="2023-02-20T13:17:57 IST" depends-on-methods="com.hrms.masters.tests.MastersPersonalTest.LoginTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MastersPersonalTest.ReligionTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MastersPersonalTest.ReligionTest()[pri:0, instance:com.hrms.masters.tests.MastersPersonalTest@479cbee5] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReligionTest -->
      </class> <!-- com.hrms.masters.tests.MastersPersonalTest -->
      <class name="com.hrms.masters.tests.MastersGeographyTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrms.masters.tests.MastersGeographyTest@4d518b32]" started-at="2023-02-20T13:13:50 IST" name="setup" finished-at="2023-02-20T13:13:58 IST" duration-ms="8660" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="LoginTest()[pri:0, instance:com.hrms.masters.tests.MastersGeographyTest@4d518b32]" started-at="2023-02-20T13:13:58 IST" name="LoginTest" finished-at="2023-02-20T13:14:14 IST" duration-ms="16201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method signature="AreaEditTest()[pri:0, instance:com.hrms.masters.tests.MastersGeographyTest@4d518b32]" started-at="2023-02-20T13:14:15 IST" name="AreaEditTest" finished-at="2023-02-20T13:14:18 IST" depends-on-methods="com.hrms.masters.tests.MastersGeographyTest.LoginTest" duration-ms="3009" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AreaEditTest -->
        <test-method signature="AreaTest()[pri:0, instance:com.hrms.masters.tests.MastersGeographyTest@4d518b32]" started-at="2023-02-20T13:14:18 IST" name="AreaTest" finished-at="2023-02-20T13:14:51 IST" depends-on-methods="com.hrms.masters.tests.MastersGeographyTest.LoginTest" duration-ms="33558" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AreaTest -->
        <test-method signature="CityEditTest()[pri:0, instance:com.hrms.masters.tests.MastersGeographyTest@4d518b32]" started-at="2023-02-20T13:14:51 IST" name="CityEditTest" finished-at="2023-02-20T13:14:53 IST" depends-on-methods="com.hrms.masters.tests.MastersGeographyTest.LoginTest" duration-ms="1743" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CityEditTest -->
        <test-method signature="CityTest()[pri:0, instance:com.hrms.masters.tests.MastersGeographyTest@4d518b32]" started-at="2023-02-20T13:14:53 IST" name="CityTest" finished-at="2023-02-20T13:15:26 IST" depends-on-methods="com.hrms.masters.tests.MastersGeographyTest.LoginTest" duration-ms="33215" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CityTest -->
        <test-method signature="CountryEditTest()[pri:0, instance:com.hrms.masters.tests.MastersGeographyTest@4d518b32]" started-at="2023-02-20T13:15:26 IST" name="CountryEditTest" finished-at="2023-02-20T13:15:48 IST" depends-on-methods="com.hrms.masters.tests.MastersGeographyTest.LoginTest" duration-ms="21918" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CountryEditTest -->
        <test-method signature="CountryTest()[pri:0, instance:com.hrms.masters.tests.MastersGeographyTest@4d518b32]" started-at="2023-02-20T13:15:48 IST" name="CountryTest" finished-at="2023-02-20T13:15:55 IST" depends-on-methods="com.hrms.masters.tests.MastersGeographyTest.LoginTest" duration-ms="7364" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CountryTest -->
        <test-method signature="StateEditTest()[pri:0, instance:com.hrms.masters.tests.MastersGeographyTest@4d518b32]" started-at="2023-02-20T13:15:55 IST" name="StateEditTest" finished-at="2023-02-20T13:16:20 IST" depends-on-methods="com.hrms.masters.tests.MastersGeographyTest.LoginTest" duration-ms="24256" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StateEditTest -->
        <test-method signature="StateTest()[pri:0, instance:com.hrms.masters.tests.MastersGeographyTest@4d518b32]" started-at="2023-02-20T13:16:20 IST" name="StateTest" finished-at="2023-02-20T13:16:30 IST" depends-on-methods="com.hrms.masters.tests.MastersGeographyTest.LoginTest" duration-ms="9891" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StateTest -->
        <test-method signature="WorklocationEditTest()[pri:0, instance:com.hrms.masters.tests.MastersGeographyTest@4d518b32]" started-at="2023-02-20T13:16:30 IST" name="WorklocationEditTest" finished-at="2023-02-20T13:17:12 IST" depends-on-methods="com.hrms.masters.tests.MastersGeographyTest.LoginTest" duration-ms="42332" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WorklocationEditTest -->
        <test-method signature="WorklocationTest()[pri:0, instance:com.hrms.masters.tests.MastersGeographyTest@4d518b32]" started-at="2023-02-20T13:17:12 IST" name="WorklocationTest" finished-at="2023-02-20T13:17:56 IST" depends-on-methods="com.hrms.masters.tests.MastersGeographyTest.LoginTest" duration-ms="43689" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WorklocationTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrms.masters.tests.MastersGeographyTest@4d518b32]" started-at="2023-02-20T13:17:58 IST" name="tearDown" finished-at="2023-02-20T13:17:59 IST" duration-ms="950" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hrms.masters.tests.MastersGeographyTest -->
    </test> <!-- HRMS automation masters -->
  </suite> <!-- HRMS -->
</testng-results>
